# ==============================================================================
# compose-koboldcpp-v1.yaml
#
# DAEMON:
#   podman-compose -f compose-koboldcpp-v1.yaml --profile daemon up -d
#
# DEBUG:
#   podman-compose -f compose-koboldcpp-v1.yaml --profile debug up
#
# Stop:
#   podman-compose -f compose-koboldcpp-v1.yaml down
#
# Logs:
#   podman logs -f kobold.cpp
#   podman logs -f kobold.cpp-daemon
# ==============================================================================

version: "3.9"

services:
  koboldcpp:
    image: localhost/rthor-kobold.cpp:alpha
    container_name: kobold.cpp
    profiles: ["debug", "daemon"]
    ports:
      - "5001:5001"
    volumes:
      - /home/brutef0rce/workspace/ai/models/gguf:/models:Z
    environment:
      KCPP_MODEL: "/models/Qwen2.5-3B.Q4_K_M.gguf"
      KCPP_THREADS: "auto"
      KCPP_CONTEXT: "4096"
    command: >
      /app/koboldcpp
      --model ${KCPP_MODEL}
      --threads ${KCPP_THREADS}
      --contextsize ${KCPP_CONTEXT}
      --api
    restart: "no"

  koboldcpp-daemon:
    image: localhost/rthor-kobold.cpp:alpha
    container_name: kobold.cpp-daemon
    profiles: ["daemon"]
    ports:
      - "5002:5001"
    volumes:
      - /home/brutef0rce/workspace/ai/models/gguf:/models:Z
    environment:
      KCPP_MODEL: "/models/Qwen2.5-3B.Q4_K_M.gguf"
      KCPP_THREADS: "auto"
      KCPP_CONTEXT: "4096"
    command: >
      /app/koboldcpp
      --model ${KCPP_MODEL}
      --threads ${KCPP_THREADS}
      --contextsize ${KCPP_CONTEXT}
      --api
    restart: always
