# podman build -t localhost/rthor-kobold.cpp:alpha -f Containerfile .
FROM debian:stable-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        git \
        cmake \
        libsdl2-dev \
        python3 \
        python3-pip \
        libnuma-dev \
        libpthread-stubs0-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/LostRuins/koboldcpp.git . && \
    make -j$(nproc)

RUN mkdir /models

EXPOSE 5001

ENTRYPOINT ["./koboldcpp"]
