FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential cmake git curl libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/ggerganov/llama.cpp /opt/llama.cpp

RUN mkdir -p /opt/llama.cpp/build && \
    cd /opt/llama.cpp/build && \
    cmake .. && \
    cmake --build . --config Release -j

RUN mkdir -p /models
VOLUME ["/models"]

WORKDIR /opt/llama.cpp
EXPOSE 8080

CMD ["bash"]
